# Generated by Django 5.2.1 on 2025-05-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_transaction_transactionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
